spring.application.name: WeatherService
server:
  port: 8080

weather:
  provider: weatherbit # all, yandex, weatherapi, weatherbit
external:
  yandex:
    weather:
      baseUrl: https://api.weather.yandex.ru
      apiVersion: /v2
      endpoint: /forecast
      apiKeyHeader: X-Yandex-API-Key
      apiKey:
      lang: ru_RU
      limit: 1
      hours: true
      extra: false
  weather.api:
      baseUrl: https://api.weatherapi.com
      apiVersion: /v1
      endpoint: /forecast.json
      apiKeyHeader: key
      apiKey:
      lang: ru
      days: 1
  weather.bit:
      baseUrl: https://api.weatherbit.io/
      apiVersion: /v2.0
      endpoint: /forecast/hourly
      apiKeyHeader: key
      apiKey:
      lang: ru
      hours: 24
      units: m
  openmap:
    street:
        baseUrl: https://nominatim.openstreetmap.org
        endpoint: /search
